### ISSUE TITLE
Pull all translations, not limited to tags

### ISSUE THREAD

**Issue by emschenn** [lokalise/lokalise-pull-action#5]
Hi,

Thank you for creating such a useful tool! 😃 

Yet I was wondering if there's a way to bypass the current limitation of only pulling translations tagged with the branch name. Instead, is it possible to pull **all** translations regardless of tags? 

I tried overriding the configuration using:
```yaml
additional_params: --include-tags ''
```
However, it doesn't seem to work. 🙏🏼

**Comment by bodrovis** [comment]
Thank you for the feedback, I'll look into it 👍

**Comment by bodrovis** [comment]
@emschenn We've discussed with the team and in general I don't see any problems introducing this feature. However, this is a very new tool and you're one of the early adopters therefore (if that's okay) can I ask what is your current use case for this feature? From my understanding, you're looking for an easy way to "just download it" with a few clicks (nothing wrong with that!), right? :)

I guess we could introduce an optional parameter to disable filtering by tags. /cc @amira-lok

**Comment by emschenn** [comment]
hi @bodrovis thanks for the swift response! 🙌

Our use case is quite straightforward:
- When new strings are added to the repo, we pull them from GitHub into Lokalise. (We're using the `po` file format, where the string itself acts as the key for its corresponding translation) 
- Once the translation is complete, we just download all the strings and send them back to GitHub via App Trigger.

**Comment by bodrovis** [comment]
Awesome, thank you for these explanations, it helps! So, it should be implemented in v3.1.0. Just set the `skip_include_tags: true` to make it skip filtering by tags
